name: glouton-daemon
base: core18
version: '1.0'
summary: daemonize glouton.
description: |
  Use this snap to send metrics to bleemeo.
  
grade: devel
confinement: devmode

apps:     
  start:
    daemon: oneshot
    command: glouton --yes-run-as-root
    plugs: 
    -hardware-observe
    -home
    -network             
    -network-bind
    -network-control
    -physical-memory-observe  
    -process-control          
    -system-observe         
 env:
    command: GLOUTON_BLEEMEO_ACCOUNT_ID= $1; GLOUTON_BLEEMEO_REGISTRATION_KEY= $2
    
 glouton:
    command: $SNAP/glouton     
architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
    
parts:
  glt-part:
    build-snaps: 
    - glouton 
